<?php
declare(strict_types=1);
function env(string $key, ?string $default=null): ?string { static $v=[]; if(!$v){$file=dirname(__DIR__).'/.env';if(is_file($file))foreach(file($file,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)as$l){if($l[0]!=='#'&&str_contains($l,'=')){[$k,$x]=explode('=',$l,2);$v[trim($k)]=trim($x);}}}return $_ENV[$key]??$v[$key]??$default;}
$prod=env('APP_ENV','production')==='production';ini_set('display_errors',$prod?'0':'1');set_exception_handler(function(Throwable $e)use($prod){error_log((string)$e);json_response(false,$prod?'Terjadi kesalahan pada server':$e->getMessage(),null,500);});
session_name('sinaesta_session');session_set_cookie_params(['httponly'=>true,'secure'=>$prod,'samesite'=>$prod?'None':'Lax','domain'=>env('SESSION_COOKIE_DOMAIN',''),'path'=>'/']);session_start();
$origin=$_SERVER['HTTP_ORIGIN']??'';$allowed=array_filter(array_map('trim',explode(',',env('FRONTEND_URL','http://localhost:5173'))));if(in_array($origin,$allowed,true)){header("Access-Control-Allow-Origin: $origin");header('Access-Control-Allow-Credentials: true');}header('Content-Type: application/json; charset=utf-8');header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');header('Referrer-Policy: strict-origin-when-cross-origin');if($_SERVER['REQUEST_METHOD']==='OPTIONS'){header('Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS');header('Access-Control-Allow-Headers: Content-Type,X-CSRF-Token');exit;}
function db():PDO{static$p;if(!$p){$dsn='mysql:host='.env('DB_HOST').';port='.env('DB_PORT','3306').';dbname='.env('DB_NAME').';charset=utf8mb4';$p=new PDO($dsn,env('DB_USER'),env('DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}return$p;}
function json_response(bool $success,string $message,mixed $data=null,int $code=200,array $errors=[]):never{http_response_code($code);echo json_encode(compact('success','message','data','errors'),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function body():array{$ct=$_SERVER['CONTENT_TYPE']??'';if(str_contains($ct,'application/json'))return json_decode(file_get_contents('php://input'),true)?:[];return $_POST;}
function user(bool $admin=false):array{if(empty($_SESSION['user_id']))json_response(false,'Silakan masuk terlebih dahulu',null,401);$s=db()->prepare('SELECT id,name,email,role,status,access_status FROM users WHERE id=? AND deleted_at IS NULL');$s->execute([$_SESSION['user_id']]);$u=$s->fetch();if(!$u||$u['status']!=='active')json_response(false,'Akun tidak dapat digunakan',null,403);if($admin&&$u['role']!=='admin')json_response(false,'Akses ditolak',null,403);return$u;}
function csrf():void{if($_SERVER['REQUEST_METHOD']==='GET')return;$given=$_SERVER['HTTP_X_CSRF_TOKEN']??'';if(!hash_equals($_SESSION['csrf']??'', $given))json_response(false,'Token keamanan tidak valid',null,419);}
function issue_csrf():string{$_SESSION['csrf']??=bin2hex(random_bytes(24));setcookie('XSRF-TOKEN',$_SESSION['csrf'],['path'=>'/','secure'=>env('APP_ENV')==='production','samesite'=>env('APP_ENV')==='production'?'None':'Lax']);return$_SESSION['csrf'];}
